-- Tesla
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Tesla', 'Model S', 2022);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Tesla', 'Model 3', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Tesla', 'Model X', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Tesla', 'Model Y', 2019);

-- BMW
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('BMW', 'i8', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('BMW', 'X5', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('BMW', 'M3', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('BMW', '320i', 2018);

-- Audi
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Audi', 'A4', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Audi', 'Q7', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Audi', 'R8', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Audi', 'A6', 2018);

-- Ford
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Ford', 'Mustang', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Ford', 'F-150', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Ford', 'Explorer', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Ford', 'Focus', 2018);

-- Volvo
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Volvo', 'XC90', 2022);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Volvo', 'S60', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Volvo', 'V90', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Volvo', 'XC60', 2019);

-- Mercedes-Benz
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Mercedes-Benz', 'C-Class', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Mercedes-Benz', 'E-Class', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Mercedes-Benz', 'S-Class', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Mercedes-Benz', 'GLE', 2021);

-- Toyota
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Toyota', 'Corolla', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Toyota', 'Camry', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Toyota', 'RAV4', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Toyota', 'Prius', 2022);

-- Honda
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Honda', 'Civic', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Honda', 'Accord', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Honda', 'CR-V', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Honda', 'Pilot', 2022);

-- Nissan
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Nissan', 'Altima', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Nissan', 'Maxima', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Nissan', 'Rogue', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Nissan', 'Leaf', 2022);

-- Hyundai
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Hyundai', 'Elantra', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Hyundai', 'Sonata', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Hyundai', 'Tucson', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Hyundai', 'Kona', 2022);

-- Kia
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Kia', 'Sorento', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Kia', 'Sportage', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Kia', 'Soul', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Kia', 'Optima', 2022);

-- Volkswagen
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Volkswagen', 'Golf', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Volkswagen', 'Passat', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Volkswagen', 'Tiguan', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Volkswagen', 'Jetta', 2022);

-- Chevrolet
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Chevrolet', 'Malibu', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Chevrolet', 'Equinox', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Chevrolet', 'Tahoe', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Chevrolet', 'Bolt', 2022);

-- Subaru
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Subaru', 'Impreza', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Subaru', 'Outback', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Subaru', 'Forester', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Subaru', 'Crosstrek', 2022);

-- Mazda
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Mazda', 'Mazda3', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Mazda', 'CX-5', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Mazda', 'MX-5 Miata', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Mazda', 'CX-9', 2022);

-- Dodge
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Dodge', 'Charger', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Dodge', 'Durango', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Dodge', 'Challenger', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Dodge', 'Journey', 2022);

-- Jeep
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Jeep', 'Grand Cherokee', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Jeep', 'Wrangler', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Jeep', 'Renegade', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Jeep', 'Compass', 2022);

-- Lexus
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Lexus', 'RX 350', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Lexus', 'NX 300', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Lexus', 'IS 300', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Lexus', 'GX 460', 2022);

-- Porsche
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Porsche', '911', 2021);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Porsche', 'Cayenne', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Porsche', 'Panamera', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Porsche', 'Macan', 2022);
