INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Tesla', 'Model S', 2022);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('BMW', 'i8', 2020);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Audi', 'A4', 2019);
INSERT INTO CAR (MANUFACTURER, MODEL, MANUFACTUREYEAR) VALUES ('Volvo', 'XC90', 2021);
